import React, { useState } from 'react';
import { useAuth } from '../../../contexts/AuthContext';

const CustomerReports = () => {
  const { currentUser } = useAuth();
  const [reportType, setReportType] = useState('sales');
  const [dateRange, setDateRange] = useState('this-month');

  const reportData = {
    sales: {
      totalOrders: 245,
      totalRevenue: '$12,450',
      avgOrderValue: '$50.82',
      topProducts: ['Banana Chips', 'Dried Mango', 'Apple Slices']
    },
    customers: {
      totalCustomers: 834,
      newCustomers: 67,
      activeCustomers: 445,
      topCustomers: ['John Smith', 'Sarah Johnson', 'Mike Brown']
    },
    returns: {
      totalReturns: 12,
      returnRate: '4.9%',
      topReasons: ['Quality Issue', 'Wrong Product', 'Damaged Package']
    }
  };

  const currentData = reportData[reportType];

  return (
    <div className="customer-reports">
      <div className="reports-header">
        <h2>📊 Customer Reports</h2>
        <p>Analyze customer data and sales performance (User Admin Only)</p>
      </div>

      <div className="report-controls">
        <div className="control-group">
          <label>Report Type:</label>
          <select value={reportType} onChange={(e) => setReportType(e.target.value)}>
            <option value="sales">Sales Report</option>
            <option value="customers">Customer Report</option>
            <option value="returns">Returns Report</option>
          </select>
        </div>

        <div className="control-group">
          <label>Date Range:</label>
          <select value={dateRange} onChange={(e) => setDateRange(e.target.value)}>
            <option value="this-week">This Week</option>
            <option value="this-month">This Month</option>
            <option value="last-month">Last Month</option>
            <option value="last-quarter">Last Quarter</option>
          </select>
        </div>
      </div>

      <div className="report-content">
        <h3>{reportType.charAt(0).toUpperCase() + reportType.slice(1)} Report for {dateRange}</h3>
        
        <div className="report-stats">
          {Object.entries(currentData).map(([key, value]) => (
            <div key={key} className="stat-card">
              <h4>{key.replace(/([A-Z])/g, ' $1').replace(/^./, str => str.toUpperCase())}</h4>
              {Array.isArray(value) ? (
                <ul>
                  {value.map((item, index) => (
                    <li key={index}>{item}</li>
                  ))}
                </ul>
              ) : (
                <p className="stat-value">{value}</p>
              )}
            </div>
          ))}
        </div>
      </div>

      <div className="report-actions">
        <button className="export-btn">📄 Export PDF</button>
        <button className="email-btn">📧 Email Report</button>
        <button className="print-btn">🖨️ Print Report</button>
      </div>

      <div className="report-info">
        <p><strong>Generated by:</strong> {currentUser?.name} ({currentUser?.role})</p>
        <p><strong>Generated on:</strong> {new Date().toLocaleDateString()}</p>
        <p><strong>Data accuracy:</strong> Real-time</p>
      </div>
    </div>
  );
};

export default CustomerReports;
